#!/bin/sh
# Host-side test for the XPRS codec: converts the spec corpus into a C include,
# builds xprs.c + test_xprs_host.c with gcc, and runs it.
#
# xprs_corpus.json is a COPY of the one in the specification repository
# (xprs-dev/spec). It is kept here rather than referenced across checkouts so
# this repo tests standalone -- but it must stay byte-identical to the spec's,
# because the whole point of it is that the codec is checked against the
# document rather than against another implementation.
set -e
cd "$(dirname "$0")"

CORPUS=./xprs_corpus.json
OUT=xprs_corpus_inc.h

python3 - "$CORPUS" > "$OUT" <<'EOF'
import json, sys
d = json.load(open(sys.argv[1]))
def esc(s):
    out = []
    for ch in s.encode():
        if ch in (0x22, 0x5C):        # " and backslash
            out.append('\\' + chr(ch))
        elif 0x20 <= ch <= 0x7E:
            out.append(chr(ch))
        else:
            out.append('\\%03o' % ch)
    return ''.join(out)
print('/* generated by test_xprs_host.sh from test/xprs_corpus.json */')
print('static const corpus_t g_corpus[] = {')
for e in d:
    print('  { "%s", %d, "%s" },' % (esc(e['wire']), e['bytes'] or -1, e['id']))
print('};')
EOF

gcc -Wall -Wextra -Werror -O1 -o /tmp/test_xprs xprs.c test_xprs_host.c
/tmp/test_xprs
