/* wrenchc -- compile a Wrench script to bytecode, on a desk.
 *
 * The firmware builds the VM with WRENCH_WITHOUT_COMPILER (see
 * common/geogram_wrench/CMakeLists.txt): upstream's own header says the
 * compiler "is not particularly memory or space efficient, for small embedded
 * systems it is strongly reccommeded (nay, required) that only bytecode be
 * executed". So the station never compiles anything; it verifies a signature
 * and runs bytecode. This is the other half of that arrangement.
 *
 * Upstream ships a CLI, but it pulls in its own test scaffolding and internal
 * templates (WRarray et al) that the amalgamated public header does not
 * export. wr_compile() is public and is all that is needed, so this is forty
 * lines instead of three thousand and has no dependency beyond the two files
 * already vendored in common/geogram_wrench/.
 *
 * Build:  tools/build_wrenchc.sh
 * Usage:  wrenchc <in.w> <out.wrb>
 *         wrenchc <in.w> <out.h> <symbol>     # C header, for the spike
 */

#include "wrench.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static char *slurp(const char *path, int *len)
{
    FILE *f = fopen(path, "rb");
    if (!f) return NULL;
    fseek(f, 0, SEEK_END);
    long n = ftell(f);
    fseek(f, 0, SEEK_SET);
    char *buf = (char *)malloc(n + 1);
    if (!buf) { fclose(f); return NULL; }
    if (fread(buf, 1, n, f) != (size_t)n) { free(buf); fclose(f); return NULL; }
    buf[n] = 0;
    fclose(f);
    *len = (int)n;
    return buf;
}

int main(int argc, char **argv)
{
    if (argc < 3) {
        fprintf(stderr, "usage: %s <in.w> <out.wrb>\n"
                        "       %s <in.w> <out.h> <symbol>\n", argv[0], argv[0]);
        return 2;
    }

    int srclen = 0;
    char *src = slurp(argv[1], &srclen);
    if (!src) { fprintf(stderr, "cannot read %s\n", argv[1]); return 1; }

    unsigned char *out = NULL;
    int outlen = 0;
    WRError err = wr_compile(src, srclen, &out, &outlen);
    if (err != WR_ERR_None) {
        fprintf(stderr, "%s: compile failed, WRError %d\n", argv[1], (int)err);
        free(src);
        return 1;
    }

    FILE *f = fopen(argv[2], argc >= 4 ? "w" : "wb");
    if (!f) { fprintf(stderr, "cannot write %s\n", argv[2]); return 1; }

    if (argc >= 4) {
        /* A C header, so the go/no-go spike can run a script with no loader,
         * no partition and no signature in the way of the measurement. */
        fprintf(f, "/* generated by tools/wrenchc from %s -- do not edit */\n"
                   "#pragma once\n#include <stdint.h>\n\n"
                   "static const uint8_t %s_bytecode[] = {",
                argv[1], argv[3]);
        for (int i = 0; i < outlen; i++)
            fprintf(f, "%s0x%02x",
                    i == 0 ? "\n    " : (i % 12 ? ", " : ",\n    "), out[i]);
        fprintf(f, "\n};\nstatic const int %s_bytecode_len = %d;\n",
                argv[3], outlen);
    } else {
        fwrite(out, 1, outlen, f);
    }
    fclose(f);

    printf("  %-28s -> %-28s %6d bytes\n", argv[1], argv[2], outlen);
    free(src);
    return 0;
}
