/* GENERATED from chat_page.html + xprs_crypto.js by tool/embed_page.py -- edit those, not this. */
#include <stddef.h>

const char XPRS_CHAT_PAGE[] =
"<!doctype html>\n"
"<!-- The hotspot chat page. SOURCE OF TRUTH: edit this file, then regenerate\n"
"     chat_page.c with tool/embed_page.py (kept beside it). The page is served\n"
"     from flash as a C string; everything is inline because a captive-portal\n"
"     WebView has no internet, no secure context and often no localStorage.\n"
"     The crypto is the XPRS section 9.1.2 short-Schnorr, validated against\n"
"     the spec's worked example (spec/XPRS.md). -->\n"
"<html><head><meta charset=\"utf-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
"<title>XPRS chat</title>\n"
"<style>\n"
"body{margin:0;font-family:system-ui,sans-serif;background:#111;color:#ddd;\n"
"     display:flex;flex-direction:column;height:100vh}\n"
"#top{background:#ff8c00;color:#000;padding:.5em .8em;font-weight:700;\n"
"     display:flex;justify-content:space-between;align-items:center}\n"
"#top small{font-weight:400}\n"
"#msgs{flex:1;overflow-y:auto;padding:.6em}\n"
".m{margin:.25em 0;padding:.45em .6em;background:#1b1b1b;border-radius:6px;\n"
"   word-wrap:break-word}\n"
".m.own{background:#0b2b12}\n"
".m .h{font-size:.75em;color:#8a8;display:flex;justify-content:space-between}\n"
".m .h .bad{color:#e66}\n"
"#bar{display:flex;gap:.4em;padding:.5em;background:#000}\n"
"#txt{flex:1;font:inherit;padding:.5em;background:#1b1b1b;color:#eee;\n"
"     border:1px solid #333;border-radius:6px}\n"
"button{font:inherit;padding:.5em 1em;background:#ff8c00;border:0;\n"
"       border-radius:6px;font-weight:700}\n"
"#setup{padding:1.2em;max-width:26em;margin:auto}\n"
"#setup input{width:100%;font:inherit;padding:.5em;margin:.4em 0;\n"
"     background:#1b1b1b;color:#eee;border:1px solid #333;border-radius:6px}\n"
"#foot{font-size:.7em;color:#666;padding:.2em .8em;background:#000}\n"
"#foot a{color:#997}\n"
".hide{display:none}\n"
"</style></head><body>\n"
"<div id=\"top\"><span id=\"call\">XPRS</span><small id=\"stat\">connecting</small></div>\n"
"<div id=\"setup\" class=\"hide\">\n"
"  <h3>Your identity</h3>\n"
"  <p>Messages are signed with a key that stays in this browser. Make a new\n"
"     one, or paste an existing nsec to keep your callsign.</p>\n"
"  <button onclick=\"genKey()\">Create new identity</button>\n"
"  <p>or</p>\n"
"  <input id=\"nsecin\" placeholder=\"nsec1...\">\n"
"  <button onclick=\"importKey()\">Import nsec</button>\n"
"  <p id=\"seterr\" style=\"color:#e66\"></p>\n"
"</div>\n"
"<div id=\"msgs\" class=\"hide\"></div>\n"
"<div id=\"bar\" class=\"hide\">\n"
"  <input id=\"txt\" maxlength=\"180\" placeholder=\"message\"\n"
"         onkeydown=\"if(event.key==='Enter')sendMsg()\">\n"
"  <button onclick=\"sendMsg()\">Send</button>\n"
"</div>\n"
"<div id=\"foot\">XPRS station &middot; <a href=\"/config\">settings</a> &middot;\n"
"  <a href=\"/api/services\">services</a> &middot; <span id=\"me\"></span></div>\n"
"<script>\n"
"\"use strict\";\n"
"// XPRS crypto for the hotspot chat page: sha256, secp256k1 (native BigInt),\n"
"// the section 9.1.2 short-Schnorr, base85 and bech32. No dependencies -- a\n"
"// captive-portal WebView has no secure context and no WebCrypto.subtle.\n"
"\n"
"// ---- sha256 (bytes in, bytes out) ----\n"
"function sha256(data){\n"
"  var K=[0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,\n"
"  0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,\n"
"  0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,\n"
"  0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,\n"
"  0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,\n"
"  0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,\n"
"  0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,\n"
"  0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2];\n"
"  var H=[0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19];\n"
"  var l=data.length, buf=new Uint8Array(((l+9+63)>>6)<<6);\n"
"  buf.set(data); buf[l]=0x80;\n"
"  var bl=l*8;\n"
"  buf[buf.length-4]=(bl>>>24)&255; buf[buf.length-3]=(bl>>>16)&255;\n"
"  buf[buf.length-2]=(bl>>>8)&255; buf[buf.length-1]=bl&255;\n"
"  var w=new Array(64);\n"
"  for(var off=0;off<buf.length;off+=64){\n"
"    for(var i=0;i<16;i++) w[i]=(buf[off+4*i]<<24)|(buf[off+4*i+1]<<16)|(buf[off+4*i+2]<<8)|buf[off+4*i+3];\n"
"    for(i=16;i<64;i++){\n"
"      var a1=w[i-15], b1=w[i-2];\n"
"      var s0=((a1>>>7)|(a1<<25))^((a1>>>18)|(a1<<14))^(a1>>>3);\n"
"      var s1=((b1>>>17)|(b1<<15))^((b1>>>19)|(b1<<13))^(b1>>>10);\n"
"      w[i]=(w[i-16]+s0+w[i-7]+s1)|0;\n"
"    }\n"
"    var a=H[0],b=H[1],c=H[2],d=H[3],e=H[4],f=H[5],g=H[6],h=H[7];\n"
"    for(i=0;i<64;i++){\n"
"      var S1=((e>>>6)|(e<<26))^((e>>>11)|(e<<21))^((e>>>25)|(e<<7));\n"
"      var ch=(e&f)^(~e&g);\n"
"      var t1=(h+S1+ch+K[i]+w[i])|0;\n"
"      var S0=((a>>>2)|(a<<30))^((a>>>13)|(a<<19))^((a>>>22)|(a<<10));\n"
"      var mj=(a&b)^(a&c)^(b&c);\n"
"      var t2=(S0+mj)|0;\n"
"      h=g;g=f;f=e;e=(d+t1)|0;d=c;c=b;b=a;a=(t1+t2)|0;\n"
"    }\n"
"    H[0]=(H[0]+a)|0;H[1]=(H[1]+b)|0;H[2]=(H[2]+c)|0;H[3]=(H[3]+d)|0;\n"
"    H[4]=(H[4]+e)|0;H[5]=(H[5]+f)|0;H[6]=(H[6]+g)|0;H[7]=(H[7]+h)|0;\n"
"  }\n"
"  var out=new Uint8Array(32);\n"
"  for(i=0;i<8;i++){out[4*i]=(H[i]>>>24)&255;out[4*i+1]=(H[i]>>>16)&255;out[4*i+2]=(H[i]>>>8)&255;out[4*i+3]=H[i]&255;}\n"
"  return out;\n"
"}\n"
"\n"
"// ---- byte/bigint helpers ----\n"
"function b2n(b){var v=0n;for(var i=0;i<b.length;i++)v=(v<<8n)|BigInt(b[i]);return v;}\n"
"function n2b(v,len){var out=new Uint8Array(len);for(var i=len-1;i>=0;i--){out[i]=Number(v&255n);v>>=8n;}return out;}\n"
"function cat(){var n=0,i,a=arguments;for(i=0;i<a.length;i++)n+=a[i].length;\n"
"  var out=new Uint8Array(n),o=0;for(i=0;i<a.length;i++){out.set(a[i],o);o+=a[i].length;}return out;}\n"
"function s2b(s){var out=new Uint8Array(s.length);for(var i=0;i<s.length;i++)out[i]=s.charCodeAt(i)&255;return out;}\n"
"function hex(b){var s='';for(var i=0;i<b.length;i++)s+=('0'+b[i].toString(16)).slice(-2);return s;}\n"
"\n"
"// ---- secp256k1 (Jacobian double-and-add; one-shot signing, speed is fine) ----\n"
"var P=2n**256n-2n**32n-977n;\n"
"var N=0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141n;\n"
"var GX=0x79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798n;\n"
"var GY=0x483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8n;\n"
"function mod(a,m){var r=a%m;return r<0n?r+m:r;}\n"
"function powmod(b,e,m){var r=1n;b=mod(b,m);while(e>0n){if(e&1n)r=r*b%m;b=b*b%m;e>>=1n;}return r;}\n"
"function inv(a,m){return powmod(mod(a,m),m-2n,m);}\n"
"// Jacobian points [X,Y,Z]; infinity Z=0\n"
"function jdbl(p){var X=p[0],Y=p[1],Z=p[2];if(Z===0n)return p;\n"
"  var A=X*X%P,B=Y*Y%P,C=B*B%P;\n"
"  var D=mod(2n*((X+B)*(X+B)%P-A-C),P);\n"
"  var E=3n*A%P,F=E*E%P;\n"
"  var X3=mod(F-2n*D,P);\n"
"  return [X3,mod(E*(D-X3)-8n*C,P),mod(2n*Y*Z,P)];}\n"
"function jadd(p,q){if(p[2]===0n)return q;if(q[2]===0n)return p;\n"
"  var Z1Z1=p[2]*p[2]%P,Z2Z2=q[2]*q[2]%P;\n"
"  var U1=p[0]*Z2Z2%P,U2=q[0]*Z1Z1%P;\n"
"  var S1=p[1]*Z2Z2%P*q[2]%P,S2=q[1]*Z1Z1%P*p[2]%P;\n"
"  if(U1===U2)return S1===S2?jdbl(p):[0n,1n,0n];\n"
"  var H=mod(U2-U1,P),I=4n*H*H%P,J=H*I%P,r=mod(2n*(S2-S1),P),V=U1*I%P;\n"
"  var X3=mod(r*r-J-2n*V,P);\n"
"  return [X3,mod(r*(V-X3)-2n*S1*J,P),mod(2n*H*p[2]%P*q[2],P)];}\n"
"function jmul(k,px,py){var r=[0n,1n,0n],q=[px,py,1n];\n"
"  while(k>0n){if(k&1n)r=jadd(r,q);q=jdbl(q);k>>=1n;}return r;}\n"
"function jaff(p){if(p[2]===0n)return null;var zi=inv(p[2],P),zi2=zi*zi%P;\n"
"  return [p[0]*zi2%P,p[1]*zi2%P*zi%P];}\n"
"function mulG(k){return jaff(jmul(mod(k,N),GX,GY));}\n"
"\n"
"// ---- tagged hash: sha256(sha256(tag)||sha256(tag)||msg) ----\n"
"function tagged(tag,msg){var th=sha256(s2b(tag));return sha256(cat(th,th,msg));}\n"
"\n"
"// ---- XPRS short-Schnorr (9.1.2) ----\n"
"function xprsSign(canonicalStr,dPriv,aux){\n"
"  var digest=sha256(s2b(canonicalStr));\n"
"  var d=mod(dPriv,N); if(d===0n) throw 'bad key';\n"
"  var Pt=mulG(d);\n"
"  if(Pt[1]&1n){d=N-d;Pt=mulG(d);}\n"
"  var px=n2b(Pt[0],32);\n"
"  var k=b2n(tagged('XPRS/nonce',cat(n2b(d,32),digest,aux)));\n"
"  k=mod(k,N); if(k===0n)k=1n;\n"
"  var R=mulG(k);\n"
"  var rx=n2b(R[0],32);\n"
"  var e32=tagged('XPRS/challenge',cat(rx,px,digest));\n"
"  var e=b2n(e32.slice(0,16));\n"
"  var s=mod(k+e*d,N);\n"
"  return cat(e32.slice(0,16),n2b(s,32));\n"
"}\n"
"\n"
"// ---- base85, the spec alphabet ----\n"
"var B85='0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ.-+=^!/*?&<>()[]%$#@,;_';\n"
"function b85enc(bytes){var out='';\n"
"  for(var i=0;i<bytes.length;i+=4){\n"
"    var v=(bytes[i]*16777216)+(bytes[i+1]*65536)+(bytes[i+2]*256)+bytes[i+3];\n"
"    var d=['','','','',''];\n"
"    for(var j=4;j>=0;j--){d[j]=B85[v%85];v=Math.floor(v/85);}\n"
"    out+=d.join('');}\n"
"  return out;}\n"
"\n"
"// ---- bech32 (npub/nsec) ----\n"
"var BC='qpzry9x8gf2tvdw0s3jn54khce6mua7l';\n"
"function bcPolymod(vals){var GEN=[0x3b6a57b2,0x26508e6d,0x1ea119fa,0x3d4233dd,0x2a1462b3];\n"
"  var chk=1;for(var i=0;i<vals.length;i++){var top=chk>>25;chk=((chk&0x1ffffff)<<5)^vals[i];\n"
"  for(var j=0;j<5;j++)if((top>>j)&1)chk^=GEN[j];}return chk;}\n"
"function bcHrpExpand(hrp){var out=[];var i;for(i=0;i<hrp.length;i++)out.push(hrp.charCodeAt(i)>>5);\n"
"  out.push(0);for(i=0;i<hrp.length;i++)out.push(hrp.charCodeAt(i)&31);return out;}\n"
"function bech32Encode(hrp,data5){var vals=bcHrpExpand(hrp).concat(data5);\n"
"  var pm=bcPolymod(vals.concat([0,0,0,0,0,0]))^1;var chk='';\n"
"  for(var i=0;i<6;i++)chk+=BC[(pm>>(5*(5-i)))&31];\n"
"  var s=hrp+'1';for(i=0;i<data5.length;i++)s+=BC[data5[i]];return s+chk;}\n"
"function bech32Decode(str){str=str.toLowerCase();var pos=str.lastIndexOf('1');\n"
"  if(pos<1||pos+7>str.length)return null;\n"
"  var hrp=str.slice(0,pos),data=[];\n"
"  for(var i=pos+1;i<str.length;i++){var d=BC.indexOf(str[i]);if(d<0)return null;data.push(d);}\n"
"  if(bcPolymod(bcHrpExpand(hrp).concat(data))!==1)return null;\n"
"  return {hrp:hrp,data:data.slice(0,-6)};}\n"
"function to5(bytes){var out=[],acc=0,bits=0;\n"
"  for(var i=0;i<bytes.length;i++){acc=(acc<<8)|bytes[i];bits+=8;\n"
"    while(bits>=5){bits-=5;out.push((acc>>bits)&31);}}\n"
"  if(bits>0)out.push((acc<<(5-bits))&31);return out;}\n"
"function to8(data5){var out=[],acc=0,bits=0;\n"
"  for(var i=0;i<data5.length;i++){acc=(acc<<5)|data5[i];bits+=5;\n"
"    while(bits>=8){bits-=8;out.push((acc>>bits)&255);}}\n"
"  return new Uint8Array(out);}\n"
"function npubEncode(pubx){return bech32Encode('npub',to5(pubx));}\n"
"function nsecEncode(priv){return bech32Encode('nsec',to5(priv));}\n"
"function nsecDecode(str){var d=bech32Decode(str);\n"
"  if(!d||d.hrp!=='nsec')return null;var b=to8(d.data);\n"
"  return b.length===32?b:null;}\n"
"\n"
"// ---- identity helpers ----\n"
"function callsignFromNpub(npub){var s='X3';\n"
"  for(var i=5;i<9;i++)s+=npub[i].toUpperCase();return s;}\n"
"function pubkeyX(privBytes){var Pt=mulG(b2n(privBytes));return n2b(Pt[0],32);}\n"
"\n"
"\n"
"\n"
"// ---- storage: localStorage -> cookie -> memory (captive WebViews) ----\n"
"var mem={};\n"
"function stGet(k){\n"
"  try{var v=localStorage.getItem(k);if(v!==null)return v;}catch(e){}\n"
"  var m=document.cookie.match(new RegExp('(?:^|; )'+k+'=([^;]*)'));\n"
"  if(m)return decodeURIComponent(m[1]);\n"
"  return mem[k]!==undefined?mem[k]:null;}\n"
"function stSet(k,v){\n"
"  try{localStorage.setItem(k,v);}catch(e){}\n"
"  try{document.cookie=k+'='+encodeURIComponent(v)+'; max-age=31536000; path=/';}catch(e){}\n"
"  mem[k]=v;}\n"
"\n"
"// ---- identity ----\n"
"var priv=null,npub='',mycall='';\n"
"function haveKey(){return priv!==null;}\n"
"function useKey(bytes){\n"
"  priv=bytes;\n"
"  npub=npubEncode(pubkeyX(priv));\n"
"  mycall=callsignFromNpub(npub);\n"
"  stSet('xprs_nsec',nsecEncode(priv));\n"
"  document.getElementById('call').textContent=mycall;\n"
"  document.getElementById('me').textContent=npub.slice(0,14)+'...';\n"
"  show(true);\n"
"}\n"
"function genKey(){\n"
"  var b=new Uint8Array(32);\n"
"  if(window.crypto&&crypto.getRandomValues)crypto.getRandomValues(b);\n"
"  else for(var i=0;i<32;i++)b[i]=Math.floor(Math.random()*256);\n"
"  if(b2n(b)===0n||b2n(b)>=N){genKey();return;}\n"
"  useKey(b);\n"
"}\n"
"function importKey(){\n"
"  var v=document.getElementById('nsecin').value.trim();\n"
"  var b=nsecDecode(v);\n"
"  if(!b||b2n(b)===0n||b2n(b)>=N){\n"
"    document.getElementById('seterr').textContent='That is not a valid nsec.';\n"
"    return;}\n"
"  useKey(b);\n"
"}\n"
"function show(chat){\n"
"  document.getElementById('setup').className=chat?'hide':'';\n"
"  document.getElementById('msgs').className=chat?'':'hide';\n"
"  document.getElementById('bar').className=chat?'':'hide';\n"
"}\n"
"\n"
"// ---- XPRS wires ----\n"
"function tsNow(){\n"
"  var d=new Date(),p=function(n){return (n<10?'0':'')+n;};\n"
"  return d.getUTCFullYear()+'-'+p(d.getUTCMonth()+1)+'-'+p(d.getUTCDate())+\n"
"    '_'+p(d.getUTCHours())+':'+p(d.getUTCMinutes())+':'+p(d.getUTCSeconds());}\n"
"function aux32(){var b=new Uint8Array(32);\n"
"  if(window.crypto&&crypto.getRandomValues)crypto.getRandomValues(b);\n"
"  else for(var i=0;i<32;i++)b[i]=Math.floor(Math.random()*256);return b;}\n"
"function signWire(canonical){\n"
"  // sig: before \" m:\" when present, else appended (mirrors xprsid_sign)\n"
"  var sig=' sig:'+b85enc(xprsSign(canonical,b2n(priv),aux32()));\n"
"  var i=canonical.indexOf(' m:');\n"
"  if(i>=0)return canonical.slice(0,i)+sig+canonical.slice(i);\n"
"  return canonical+sig;}\n"
"\n"
"// ---- sending: POST -> GET -> Image() (hostile WebViews) ----\n"
"function postWire(wire,cb){\n"
"  var done=false;\n"
"  function fin(ok){if(!done){done=true;if(cb)cb(ok);}}\n"
"  try{\n"
"    var x=new XMLHttpRequest();\n"
"    x.open('POST','/api/xprs/send',true);\n"
"    x.timeout=4000;\n"
"    x.onload=function(){fin(x.status===200);};\n"
"    x.onerror=x.ontimeout=function(){getFallback(wire,fin);};\n"
"    x.send(JSON.stringify({wire:wire}));\n"
"  }catch(e){getFallback(wire,fin);}\n"
"}\n"
"function getFallback(wire,fin){\n"
"  try{\n"
"    var x=new XMLHttpRequest();\n"
"    x.open('GET','/api/xprs/send?wire='+encodeURIComponent(wire),true);\n"
"    x.timeout=4000;\n"
"    x.onload=function(){fin(x.status===200);};\n"
"    x.onerror=x.ontimeout=function(){\n"
"      try{new Image().src='/api/xprs/send?wire='+encodeURIComponent(wire);}catch(e){}\n"
"      fin(true);};\n"
"    x.send();\n"
"  }catch(e){fin(false);}\n"
"}\n"
"\n"
"var identSent=0;\n"
"function sendIdentity(){\n"
"  var now=Date.now();\n"
"  if(now-identSent<86400000)return;\n"
"  identSent=now;\n"
"  postWire(signWire('t:identity f:'+mycall+' ts:'+tsNow()+' k:'+npub),null);\n"
"}\n"
"function sendMsg(){\n"
"  var t=document.getElementById('txt');\n"
"  var text=t.value.trim();\n"
"  if(!text||!haveKey())return;\n"
"  text=text.replace(/[\\x00-\\x1f]/g,' ');\n"
"  sendIdentity();\n"
"  var wire=signWire('t:message f:'+mycall+' ts:'+tsNow()+' m:'+text);\n"
"  if(wire.length>250){\n"
"    document.getElementById('stat').textContent='too long';\n"
"    return;}\n"
"  t.value='';\n"
"  postWire(wire,function(ok){\n"
"    document.getElementById('stat').textContent=ok?'sent':'send failed';\n"
"    setTimeout(load,400);});\n"
"}\n"
"\n"
"// ---- receiving: poll the station's archive ----\n"
"var seen={};\n"
"function render(row){\n"
"  var w=row.wire||'';\n"
"  if(seen[w])return;seen[w]=1;\n"
"  var mi=w.indexOf(' m:');\n"
"  var text=mi>=0?w.slice(mi+3):'';\n"
"  if(!text)return;\n"
"  var d=document.createElement('div');\n"
"  d.className='m'+(row.from===mycall?' own':'');\n"
"  var when=row.ts?new Date(row.ts*1000).toLocaleTimeString():'';\n"
"  var sig=row.sig==='verified'?' &#10003;':(row.sig==='none'?' <span class=bad>unsigned</span>':'');\n"
"  d.innerHTML='<div class=\"h\"><span></span><span>'+when+sig+'</span></div><div></div>';\n"
"  d.children[0].children[0].textContent=row.from;\n"
"  d.children[1].textContent=text;\n"
"  var box=document.getElementById('msgs');\n"
"  box.appendChild(d);\n"
"  box.scrollTop=box.scrollHeight;\n"
"}\n"
"function load(){\n"
"  try{\n"
"    var x=new XMLHttpRequest();\n"
"    x.open('GET','/api/xprs/history?only=message&limit=50',true);\n"
"    x.timeout=4000;\n"
"    x.onload=function(){\n"
"      try{\n"
"        var d=JSON.parse(x.responseText);\n"
"        var rows=(d.rows||[]).slice().reverse();  // oldest first for append\n"
"        for(var i=0;i<rows.length;i++)render(rows[i]);\n"
"        document.getElementById('stat').textContent=\n"
"          (d.held!==undefined?d.held+' held':'ok');\n"
"      }catch(e){}\n"
"    };\n"
"    x.send();\n"
"  }catch(e){}\n"
"}\n"
"\n"
"// ---- boot ----\n"
"(function(){\n"
"  var saved=stGet('xprs_nsec');\n"
"  if(saved){var b=nsecDecode(saved);if(b){useKey(b);}}\n"
"  if(!haveKey())show(false);\n"
"  load();\n"
"  setInterval(load,3000);\n"
"})();\n"
"</script></body></html>\n"
"\n";

const size_t XPRS_CHAT_PAGE_LEN = sizeof(XPRS_CHAT_PAGE) - 1;
